name: Orders Service CI/CD

on:
  push:
    branches:
      - main
      - develop
      - test
  pull_request:
    branches:
      - main
      - develop
      - test

jobs:
  call-backend-ci-cd:
    uses: entrega-devops-agosto-nicolas-banales/devops-configuration/.github/workflows/backend-ci-cd.yml@main
    with:
      service-name: 'orders-service'
      environment: ${{ github.ref == 'refs/heads/main' && 'prod' || (github.ref == 'refs/heads/develop' && 'dev' || 'test') }}
    secrets:
      dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
      sonar-token: ${{ secrets.SONAR_TOKEN }}
      sonar-host-url: ${{ secrets.SONAR_HOST_URL }}
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
